FROM nginx:1.25

RUN apt-get update --fix-missing
RUN mkdir -p /usr/src/app/src

WORKDIR /usr/src/app

RUN apt-get install -y curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

COPY package.json .
COPY package-lock.json .
COPY .browserslistrc .
COPY .postcssrc.js .
COPY vue.config.js .
COPY tsconfig.json .

RUN npm ci

COPY . /usr/src/app
RUN npm run build

WORKDIR /etc/nginx
