FROM nginx:1.25

RUN apt-get update --fix-missing
RUN mkdir -p /usr/src/app/src

WORKDIR /usr/src/app

RUN apt-get install -y curl gnupg wget
RUN wget https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.gz
RUN tar -xf node-v16.9.1-linux-x64.tar.gz -C /usr/local --strip-components=1 --no-same-owner

COPY package.json .
COPY package-lock.json .
COPY .browserslistrc .
COPY .postcssrc.js .
COPY vue.config.js .
COPY tsconfig.json .

RUN npm ci

COPY . /usr/src/app
RUN npm run build

WORKDIR /etc/nginx
