FROM ubuntu:jammy

RUN mkdir -p /usr/src/app/src
RUN apt-get update --fix-missing

WORKDIR /usr/src/app

RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

COPY package.json .
COPY package-lock.json .
COPY .browserslistrc .
COPY .postcssrc.js .
COPY vue.config.js .
COPY tsconfig.json .

RUN npm ci
