# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, release* ]
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for release'
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Yes, we're running this on each step because I couldn't figure out
    # the quirks of uploading/downloading artifacts into the right
    # directory
    - name: Update version number (on dispatch only)
      run: ./dev_scripts/ci/update_version_number.sh "${{ inputs.version }}"

    - run: npm ci
    - run: npm run lint
    - run: npm run build

  unit-tests:
    # Lint is fast. If we wait for it we guarantee a cache hit on dependencies.
    needs: lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Yes, we're running this on each step because I couldn't figure out
    # the quirks of uploading/downloading artifacts into the right
    # directory
    - name: Update version number (on dispatch only)
      run: ./dev_scripts/ci/update_version_number.sh "${{ inputs.version }}"

    - run: npm ci
    - run: npm test

  e2e-tests:
    # Lint is fast. If we wait for it we guarantee a cache hit on dependencies.
    needs: lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Yes, we're running this on each step because I couldn't figure out
    # the quirks of uploading/downloading artifacts into the right
    # directory
    - name: Update version number (on dispatch only)
      run: ./dev_scripts/ci/update_version_number.sh "${{ inputs.version }}"

    - run: docker compose -f e2e_test_stack/docker-compose.yml build
    - run: docker compose -f e2e_test_stack/docker-compose.yml pull

    - run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - run: npm run e2e:once

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    if: github.event_name == 'workflow_dispatch'

    needs:
    - lint
    - unit-tests
    - e2e-tests

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases

    steps:
      # See https://github.com/organizations/eecs-autograder/settings/apps
      # and https://github.com/orgs/community/discussions/25305#discussioncomment-8256560
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      # Yes, we're running this on each step because I couldn't figure out
      # the quirks of uploading/downloading artifacts into the right
      # directory
      - name: Update version number (on dispatch only)
        run: ./dev_scripts/ci/update_version_number.sh "${{ inputs.version }}"

      - name: Commit updated version files
        run: |
          git add package.json package-lock.json
          git commit -m "Version ${{ inputs.version }}"
          git push
          git tag ${{ inputs.version }}
          git push --tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "${{ inputs.version }}"
          --repo "$GITHUB_REPOSITORY"
          --notes ""
